# Site settings
title: "Maylychko Ilya. Resume for Code reviewer HTML/CSS"
description: Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Maylychko Ilya"
resume_title:                   "Code reviewer HTML/CSS"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "juggler39@yandex.ru"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "8-911-866-0001"
resume_contact_address:         "108 Krasnoselskaya Street, Kaliningrad"

resume_header_contact_info:     "108 Krasnoselskaya Street, Kaliningrad • 8-911-866-0001 • juggler39@yandex.ru"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am excited to submit my application for the position of Code reviewer HTML/CSS with Yandex.
Your company is really exiting and I appreciate the devotion to serving your customer’s needs.
I believe my skills and my background make me an excellent fit for this position.
I have a great experience with HTML and CSS, which I used for many different projects.
The level of my English knowledge is deep enough to speak fluently without any especial troubles and write texts without mistakes.
I would like to contact with you and discuss the position in detail.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/juggler39"
  resume_twitter_url:           "#"
  resume_dribbble_url:          "#"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "#r"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "#"
  resume_medium_url:            "#"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-modernist
